### ISSUE TITLE
出现大量源直播间没有的弹幕

### ISSUE THREAD

**Issue by Hitseditor** [guyijie1211/JustLive-Web#15]
![无标题](https://user-images.githubusercontent.com/36365639/136449564-5fc3dbec-65b9-4a06-8fcb-5e3711b92b8e.png)
同样的的直播间，都没看任何过滤。不知道是抓取错误还是什么原因，关键是发的垃圾弹幕还都跟直播间有关不是纯随机，怀疑是水军吧，在斗鱼直接看又没有
https://www.douyu.com/topic/CSGO2C?rid=9418

**Comment by guyijie1211** [comment]
部分斗鱼直播间是存在这个问题，我有空看一下
