### ISSUE TITLE
斗鱼的分区是有做隐藏处理了吗

### ISSUE THREAD

**Issue by vxbmtu94516** [guyijie1211/JustLive-Web#21]
怎么官方api可以获取到的分区用这个项目的就没有
![image](https://user-images.githubusercontent.com/89058555/139652061-5b58bb01-a6d9-4cec-b01c-cdd238288431.png)

**Comment by guyijie1211** [comment]
发现一个奇怪的事情，在Java代码中用httpclient 和在postman中 调用这个官方接口的结果是不一样的。虽然获取到分区数量都是2922个，但是其中的内容是不一样的。而"一起看"这个分区在代码中获取不到。上图是postman的结果，下图是代码的结果。
![postman](https://user-images.githubusercontent.com/23636549/139662661-ed41f079-47bc-42ee-a85b-271ce726ade1.png)
![屏幕截图 2021-11-01 190902](https://user-images.githubusercontent.com/23636549/139662709-8a332209-a190-455f-86e1-bfb820d7c964.png)
见鬼了，容我再查一下

**Comment by guyijie1211** [comment]
找到问题了，请求头的问题。这斗鱼太搞了

**Comment by vxbmtu94516** [comment]
2021年11月11日 问题复现了
