### ISSUE TITLE
BUG：虎牙、斗鱼打开视频已经不能刷新出来，而且默认开启idm下载是什么鬼？

### ISSUE THREAD

**Issue by jkqxl** [guyijie1211/JustLive-Web#215]
问题如标题，B站、CC倒是没什么问题。

浏览器是有 IDM插件 的，但软件并没有打开，就是一点击视频就开始下载，但真正的视频却无法刷新出来。

**Comment by HBGIEHGI** [comment]
去idm下载设置里把文件类型里的m3u8和m4s去掉
