### ISSUE TITLE
可以把真实直播源 展示出来吗。

### ISSUE THREAD

**Issue by wzrove** [guyijie1211/JustLive-Web#29]
如题，想用第三方播放器看。

**Comment by guyijie1211** [comment]
抱歉回复晚。进入直播间之前f12 打开开发者工具，然后进入直播间，在网络(network)标签下搜索getRealUrl就可以看到。
![image](https://user-images.githubusercontent.com/23636549/153851970-894a4679-2682-4e3a-b1b1-da54a1dd4160.png)
