### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by fanghaook** [guyijie1211/JustLive-Web#44]
1.现在推荐页的展示逻辑是热度从高到低，但又不完全是，因为滑到下面后又会有新的热度从高到低的序列，我的建议还是直接全直播热度从高到低就好，不需要分序列，毕竟主要观看还是那些热度高的直播；
2.现在直播点击是直接覆盖原浏览器标签，我觉得生成新标签页更好，因为经常多直播间一起看。或者直播间右键有在新的便签页打开的选项，但现在右键打开的是保存图片相关操作；
3.搜索主播框没有回车搜索功能；
4.有时候多次点击关注列表按键关注的主播会重复出现两次。
我是看lks的视频知道的您的网站，可以说是相见恨晚，感谢，确实是特别好用，不用再多个app或网站来回折腾，我的建议只是我使用过程中出现的小问题，算是鸡蛋里挑骨头，希望作者越做越好！

**Comment by guyijie1211** [comment]
1、因为我不是拉取全量直播间的，所以这个暂时没法解决.
2、现在已经增加新标签打开直播间功能
3、已增加
4、有空回看看
