### ISSUE TITLE
弹幕在登陆后加载失败

### ISSUE THREAD

**Issue by iiijam** [guyijie1211/JustLive-Web#47]
在Chrome 99.0.4844.51（正式版本） （64 位）校园网上 存在无法加载弹幕的问题
已关闭所有拓展，代理软件
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/157650696-4165f06f-a6c9-4f7a-8f43-7d3dc5ac39c8.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/157650933-3af52130-f135-44b4-9c28-f4ed64363745.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/157651952-aebdea05-6af0-4f08-9efa-3473450e9cbc.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/157652026-ca3187b0-7bd3-41b3-91f6-5d9a7a421362.png">

**Comment by guyijie1211** [comment]
是不是校园网的问题，手机流量能连上弹幕吗

**Comment by iiijam** [comment]
修复了，彻底删除屏蔽列表后好了，只不过同屏密度刷新后就失效
