### ISSUE TITLE
自动播放

### ISSUE THREAD

**Issue by Zruiry** [guyijie1211/JustLive-Web#51]
能否加上自动播放的按钮，打开按钮的时候进入直播页自动播放

**Comment by guyijie1211** [comment]
默认就是自动播放的，你看下你浏览器的设置有没有允许媒体自动播放

**Comment by Zruiry** [comment]
> 默认就是自动播放的，你看下你浏览器的设置有没有允许媒体自动播放

谷歌浏览器版本 100.0.4896.60（正式版本） （64 位）找不到媒体自动播放的相关设置

**Comment by guyijie1211** [comment]
https://user-images.githubusercontent.com/23636549/161370105-a9e066f2-9d37-4889-a90a-40eecc417f4b.mp4

**Comment by Zruiry** [comment]
> 2022-04-02.14-26-39.mp4

可以，感谢，另外网易CC的直播好像都播放不了

**Comment by Zruiry** [comment]
> > 2022-04-02.14-26-39.mp4
> 
> 可以，感谢，另外网易CC的直播好像都播放不了



> 2022-04-02.14-26-39.mp4

哦，不是，是有些播放不了
