### ISSUE TITLE
大佬你好，请问能整合一个TV端的版本吗？

### ISSUE THREAD

**Issue by sywguoyang** [guyijie1211/JustLive-Web#67]
现在电视看直播的话是安装您的APP版本，然后用飞鼠遥控器看的，用起来挺不方便的。可以的话能开发个TV版本的吗？另外搜索主播里，有一些主播搜不到。

**Comment by robinlsf** [comment]
现在只能用鼠标控制，小米电视遥控不能操作。希望能出个TV版本

**Comment by redfatguy** [comment]
> 现在只能用鼠标控制，小米电视遥控不能操作。希望能出个 TV 版本

+1
