### ISSUE TITLE
弹幕

### ISSUE THREAD

**Issue by 2462732849** [guyijie1211/JustLive-Web#72]
如果弹幕可以调节就好了。比如大小透明度之类的。

**Comment by guyijie1211** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    可以调节的啊，你找找
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年4月30日 ***@***.***> 写道： 




如果弹幕可以调节就好了。比如大小透明度之类的。

**Comment by 2462732849** [comment]
找到了，谢谢大佬
