### ISSUE TITLE
希望加个弹幕透明度调整

### ISSUE THREAD

**Issue by qq50185359** [guyijie1211/JustLive-Web#81]
希望加个弹幕透明度调整，看比赛时想看弹幕但是弹幕太多又有点挡画面

**Comment by guyijie1211** [comment]
可以调的，你找一下





------------------ 原始邮件 ------------------
发件人: qq50185359 ***@***.***&gt;
发送时间: 2022年5月15日 15:45
收件人: guyijie1211/JustLive-Web ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [guyijie1211/JustLive-Web] 希望加个弹幕透明度调整 (Issue #81)
